### ISSUE TITLE
[Incompatibility] Not compatible with LevelZ

### ISSUE THREAD

**Issue by Rad586** [Tfarcenim/Daves-Potioneering#13]
Game version: 1.18.2 fabric
Mod version: 1.0.9
Description(generated by mixin conflict helper): 
[LevelZ](https://github.com/Globox1997/LevelZ) is conflicting with [Dave's Potioneering](https://github.com/Tfarcenim/Daves-Potioneering).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE_ASSIGN") on net/minecraft/class_1812::finishUsingMixin with priority 1000 cannot inject into net/minecraft/class_1812::method_7861(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;)Lnet/minecraft/class_1799; merged by tfar.davespotioneering.mixin.PotionItemMixin with priority 1000 [PREINJECT Applicator Phase -> levelz.mixins.json:item.PotionItemMixin from mod levelz -> Prepare Injections ->  -> localvar$znj000$finishUsingMixin(Ljava/util/List;Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;)Ljava/util/List; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2378.method_10234(class_2378.java:192)
	at net.minecraft.class_2378.method_40280(class_2378.java:352)
	at net.minecraft.class_2378.method_34031(class_2378.java:300)
	at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
	at net.minecraft.class_2378.<clinit>(class_2378.java:299)
	at net.minecraft.class_2966.method_12851(class_2966.java:49)
	at net.minecraft.client.main.Main.main(Main.java:153)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- blue_endless_jankson 1.2.1 via jankson
- cloth-basic-math 0.6.0 via cloth-config
- cloth-client-events-v0 3.2.64 via davespotioneering
- cloth-config 6.2.57
- davespotioneering fabric-1.18.2-1.0.9
- fabric-api 0.67.1+1.18.2
- fabric-api-base 0.4.5+64b7c69360 via fabric-api
- fabric-api-lookup-api-v1 1.6.3+2373a54560 via fabric-api
- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560 via fabric-api
- fabric-command-api-v1 1.1.10+d7c144a860 via fabric-api
- fabric-commands-v0 0.2.9+b4f4f6cd60 via fabric-api
- fabric-containers-v0 0.1.24+d7c144a860 via fabric-api
- fabric-content-registries-v0 3.1.2+c85f2e3860 via fabric-api
- fabric-convention-tags-v1 1.0.2+474e4f7960 via fabric-api
- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
- fabric-data-generation-api-v1 3.0.3+9fcb91d260 via fabric-api
- fabric-dimensions-v1 2.1.21+489d6f8260 via fabric-api
- fabric-entity-events-v1 1.4.9+d7c144a860 via fabric-api
- fabric-events-interaction-v0 0.4.20+d7c144a860 via fabric-api
- fabric-events-lifecycle-v0 0.2.21+d7c144a860 via fabric-api
- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
- fabric-item-api-v1 1.6.1+a6f01b2660 via fabric-api
- fabric-item-groups-v0 0.3.15+91896a4960 via fabric-api
- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
- fabric-lifecycle-events-v1 2.1.1+cc71601c60 via fabric-api
- fabric-loot-api-v2 1.1.1+1997ad1260 via fabric-api
- fabric-loot-tables-v1 1.1.3+e747827960 via fabric-api
- fabric-mining-level-api-v1 2.1.5+cc71601c60 via fabric-api
- fabric-models-v0 0.3.7+d7c144a860 via fabric-api
- fabric-networking-api-v1 1.0.24+2d30af4b60 via fabric-api
- fabric-networking-v0 0.3.11+b4f4f6cd60 via fabric-api
- fabric-object-builder-api-v1 2.1.4+032c981d60 via fabric-api
- fabric-particles-v1 0.2.13+526dc1ac60 via fabric-api
- fabric-registry-sync-v0 0.9.12+bb2e047760 via fabric-api
- fabric-renderer-api-v1 0.4.16+ee3621fc60 via fabric-api
- fabric-renderer-indigo 0.5.6+41a02c8a60 via fabric-api
- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60 via fabric-api
- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60 via fabric-api
- fabric-rendering-v0 1.1.14+b4f4f6cd60 via fabric-api
- fabric-rendering-v1 1.10.8+54e5b2ec60 via fabric-api
- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
- fabric-screen-api-v1 1.0.11+d882b91560 via fabric-api
- fabric-screen-handler-api-v1 1.2.3+1f6558e860 via fabric-api
- fabric-textures-v0 1.0.13+3ac43d9560 via fabric-api
- fabric-transfer-api-v1 1.6.4+f4563ac860 via fabric-api
- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
- fabricloader 0.14.10
- jankson 4.0.0+j1.2.0 via libgui
- java 19
- levelz 1.3.4
- libgui 5.3.0+1.18 via levelz
- libninepatch 1.1.0 via libgui
- minecraft 1.18.2
- mixin-conflict-helper 1.2.0
```

## Game info
Minecraft Version: 1.18.2
Fabric Loader Version: 0.14.10

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*

Log:
[latest.txt](https://github.com/Tfarcenim/Daves-Potioneering/files/10910456/latest.txt)

**Comment by Tfarcenim** [comment]
fixed in 1.1.1
